source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StatusBarNotificationCenter_Example' do
  pod "StatusBarNotificationCenter", :path => "../"
end

target 'StatusBarNotificationCenter_Tests' do
  pod "StatusBarNotificationCenter", :path => "../"

  
end
