source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StatusBarNotificationCenter_Example', :exclusive => true do
  pod "StatusBarNotificationCenter", :path => "../"
end

target 'StatusBarNotificationCenter_Tests', :exclusive => true do
  pod "StatusBarNotificationCenter", :path => "../"

  
end
